### ISSUE TITLE
talk.js Febuary Meetup (active)

### ISSUE THREAD

**Issue by soareschen** [SingaporeJS/organizers#22]
We have new organizers helping out for the next meetup! @ongmin @jsstrn @caalberts @shawnlimws
Let's start by making a list of TODO tasks:

**To-do tasks**
- [x] Date: 22 Feb (Monday)
- [x] Venue: PayPal?
- [x] Food sponsor: PayPal?
- [ ] Speakers
- [x] Announce on [SingaporeJS Meetup](http://www.meetup.com/Singapore-JS/) - to be edited with confirmed talks at [February Meetup Link](http://www.meetup.com/Singapore-JS/events/228630145/)
- [x] Announce on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/discussions)
- [x] Announce on [SingaporeJS Facebook](https://www.facebook.com/groups/488579174512027)
- [ ] Reminder on all of the above a day before talk
- [ ] Get links to slides from all speakers, paste into comments section of meetup page.

**Suggested Topics (if checked === confirmed)**
- [x] 7 min: JavaScript News - Tim Oxley (@timoxley)
- [x] JS1k - Joshua Koo (@zz85)
- [x] Meteor JS + Interactive dance performance (@calvintan) 
- [x] loopback.io Framework: Models, Phases and Identities (@stwissel)
- [ ] Ember.js - Sherman Chen 
- [ ] Nativefier - Jia Hao - next month

<== Hit max # of speakers for this month :100:  ==>

**Format**
- Thank sponsors
- Welcome newcomers
- Presentations
- Slide: Announcements
- Shoutouts - come around to the mic

**Comment by zz85** [comment]
who suggested me? :scream: (on another hand I think I spoke on js1k at talk.js a couple years ago?)

**Comment by ongmin** [comment]
@zz85 I think Tim did.. :see_no_evil: if you're coming, would you like to speak quickly about it? the crowd changes, it wouldn't seem like a repeat (if you don't mind talking about it again..)

**Comment by notthetup** [comment]
@zz85 You encourage people to participate leh.. maybe give a few tips suggesting how they can get started.. :)

**Comment by zz85** [comment]
Ok, guess I will be back by popular demand! :grin:

**Comment by ongmin** [comment]
:+1: :smile:

**Comment by joerx** [comment]
Thought the gulp talk was off due being same same as Soares' earlier talk? :open_mouth:

**Comment by ongmin** [comment]
Updated, sorry, missed that. :see_no_evil: 
Didn't see it on [engineer.sg's archives](https://engineers.sg/episodes/search?search=talk.js), only saw Zell's last september.

**Comment by soareschen** [comment]
@joerx you can still find a different topic or talk about something different on the same subject. ;)

@ongmin shall we finalize the schedule?

**Comment by ongmin** [comment]
@soareschen @jsstrn ok! So the ones above with checks are confirmed. So if we estimate 15mins for the 4 confirmed topics + Tim's news 7 mins = 67mins.

**Comment by joerx** [comment]
@soareschen - let's aim for the next meetup. plenty of time to think about sthg. ;)

**Comment by ongmin** [comment]
Thank you @stwissel, @zz85 @calvintan for the talks today! :) They were awesome!

=== It's a wrap! :tada: ===
