### ISSUE TITLE
talk.js April Meetup

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/organizers#25]
**To-do tasks**
- [x] Date: 14th April 2016 (Thursday)
- [x] Venue: Paypal
- [x] Food sponsor: Paypal
- [x] Speakers
- [x] Announce on [SingaporeJS Meetup Page](http://www.meetup.com/Singapore-JS/) - [April's Talk.JS](http://www.meetup.com/Singapore-JS/events/229811309/)
- [x] Announce on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/discussions)
- [x] Announce on [SingaporeJS Facebook Group](https://www.facebook.com/groups/488579174512027)
- [x] Reminder on all of the above a day before talk
- [x] Get links to slides from all speakers, paste into comments section of meetup page.

**Suggested Topics (if checked === confirmed)**
- [x] Nativefier - Jia Hao (@jiahaog)
- [x] RxJS - Ryan Dao
- [x] Motion detection in yo' browser - Sher Minn
- [x] JS Performance - Huiren Woo (@giantcrab)

<== Interested to speak next month?  ==>

**Format**
- Thank sponsors
- Welcome newcomers
- Presentations
- Slide: Announcements
- Shoutouts - come around to the mic

**Comment by soareschen** [comment]
The founder of Ghost, John O'Nolan, will be coming to Singapore next month to re-incorporate Ghost in Singapore: https://blog.ghost.org/moving-to-singapore/

We should reach out to him and ask him give a special talk for next meetup.

**Comment by vshivam** [comment]
Hi guys! How do I go about proposing a talk ? Something along the lines of JavaScript and Internet of Things.

**Comment by GIANTCRAB** [comment]
Hello! Is there any room left for speakers? I would be happy to speak about JS Performance.

**Comment by ongmin** [comment]
@GIANTCRAB  Updated the Speakers. :)

**Comment by ongmin** [comment]
**Moved to May**
- [x] Ambient Dynamix : JS and IoT -  Shivam Verma (@vshivam)

**Comment by jsstrn** [comment]
@ongmin I suggest closing this issue and opening a new one for each new event.
