### ISSUE TITLE
Chitchat with John O'Nolan

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/organizers#28]
(if checked === confirmed)**

**To-do tasks**
- [ ] Date: Between 03-13 March
- [ ] Venue: PayPal?
- [ ] Food sponsor: PayPal?
- [ ] Announce on [SingaporeJS Meetup](http://www.meetup.com/Singapore-JS/) - more details to be updated at [Meetup: Chitchat with Ghost](http://www.meetup.com/Singapore-JS/events/229250360/)
- [ ] Announce on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/discussions)
- [ ] Announce on [SingaporeJS Facebook](https://www.facebook.com/groups/488579174512027)
- [ ] Reminder on all of the above a day before talk

**Questions
- [ ] ?

Please post all questions you would like to ask below: :dancer:

**Comment by sayanee** [comment]
:+1: I'm ok with PayPal - any choice of the date? I guess gotta ask PayPal

**Comment by sayanee** [comment]
Any updates on this? Let's get the venue confirmed asap so that we can avoid any schedule clashes :smiley:

**Comment by ongmin** [comment]
Post-event comments
- This complementary topic was very well received and enjoyed by attendees.
